import { useRoute } from "wouter";
import { Sidebar } from "@/components/Sidebar";
import { PageHeader } from "@/components/PageHeader";
import { useBrief } from "@/hooks/use-briefs";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Loader2, ArrowLeft, Check, Copy } from "lucide-react";
import { Link } from "wouter";
import { useToast } from "@/hooks/use-toast";

export default function BriefDetail() {
  const [match, params] = useRoute("/briefs/:id");
  const briefId = params?.id!;
  const { data: brief, isLoading } = useBrief(briefId);
  const { toast } = useToast();

  if (isLoading) return <div className="flex h-screen items-center justify-center"><Loader2 className="animate-spin" /></div>;
  if (!brief) return <div className="p-8">Brief not found</div>;

  const copyToClipboard = (text: string) => {
    navigator.clipboard.writeText(text);
    toast({ title: "Copied to clipboard" });
  };

  return (
    <div className="flex min-h-screen bg-muted/20">
      <Sidebar />
      <main className="flex-1 ml-64 p-8">
        <Link href={`/clients/${brief.clientId}`} className="inline-flex items-center text-sm text-muted-foreground hover:text-primary mb-4 transition-colors">
          <ArrowLeft className="w-4 h-4 mr-1" /> Back to Client
        </Link>

        <PageHeader 
          title={brief.title} 
          description={`Generated by ${brief.generatedBy} on ${new Date(brief.createdAt!).toLocaleDateString()}`}
        >
          <div className="flex items-center gap-2">
            <Badge variant={brief.status === 'approved' ? 'default' : 'secondary'} className="text-sm px-3 py-1">
              {brief.status.toUpperCase()}
            </Badge>
            {/* Future: Add Update/Approve buttons */}
          </div>
        </PageHeader>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          {/* Main Content */}
          <div className="lg:col-span-2 space-y-6">
            <Card>
              <CardHeader>
                <CardTitle>Suggested Angle</CardTitle>
              </CardHeader>
              <CardContent>
                <p className="leading-relaxed text-foreground/90">{brief.angle}</p>
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle>Key Points</CardTitle>
              </CardHeader>
              <CardContent>
                <ul className="list-disc pl-5 space-y-2">
                  {brief.keyPoints?.map((point, i) => (
                    <li key={i} className="text-foreground/90">{point}</li>
                  ))}
                </ul>
              </CardContent>
            </Card>
          </div>

          {/* Sidebar Info */}
          <div className="space-y-6">
            <Card>
              <CardHeader>
                <CardTitle className="text-lg">Suggested Copy</CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="bg-muted p-4 rounded-lg text-sm font-mono whitespace-pre-wrap">
                  {brief.suggestedCopy || "No copy suggested."}
                </div>
                <Button 
                  variant="outline" 
                  className="w-full" 
                  onClick={() => copyToClipboard(brief.suggestedCopy || "")}
                  disabled={!brief.suggestedCopy}
                >
                  <Copy className="w-4 h-4 mr-2" /> Copy Text
                </Button>
              </CardContent>
            </Card>
          </div>
        </div>
      </main>
    </div>
  );
}
